<?php

namespace App\Enums\Auth;

use Spatie\Enum\Enum;

/**
 * @method static self userIndex()
 * @method static self userRead()
 * @method static self userWrite()
 * @method static self userUpdate()
 * @method static self userDelete()
 * @method static self userRestore()
 * @method static self userForceDelete()
 * @method static self userAssignRole()
 * @method static self userAssignPermission()
 * @method static self userRevokeRole()
 * @method static self userRevokeLicense()
 * @method static self userBlockIndex()
 * @method static self userBlockRead()
 * @method static self userBlockWrite()
 * @method static self userBlockDelete()
 * @method static self userBlockForceDelete()
 * @method static self userBlockRestore()
 * @method static self tokenIndex()
 * @method static self tokenRead()
 * @method static self tokenWrite()
 * @method static self tokenUpdate()
 * @method static self tokenDelete()
 * @method static self tokenForceDelete()
 * @method static self tokenRestore()
 * @method static self roleIndex()
 * @method static self roleRead()
 * @method static self roleWrite()
 * @method static self roleUpdate()
 * @method static self roleDelete()
 * @method static self roleRestore()
 * @method static self roleForceDelete()
 * @method static self roleAssignPermission()
 * @method static self roleRevokePermission()
 * @method static self permissionIndex()
 * @method static self permissionRead()
 * @method static self permissionWrite()
 * @method static self permissionUpdate()
 * @method static self permissionDelete()
 * @method static self permissionRestore()
 * @method static self permissionForceDelete()
 * @method static self licenseIndex()
 * @method static self licenseRead()
 * @method static self licenseWrite()
 * @method static self licenseUpdate()
 * @method static self licenseDelete()
 * @method static self licenseRestore()
 * @method static self licenseForceDelete()
 * @method static self licenseAssignUser()
 * @method static self siteMapIndex()
 * @method static self siteMapRead()
 * @method static self siteMapWrite()
 * @method static self siteMapUpdate()
 * @method static self siteMapDelete()
 * @method static self siteMapRestore()
 * @method static self siteMapForceDelete()
 * @method static self postIndex()
 * @method static self postRead()
 * @method static self postWrite()
 * @method static self postUpdate()
 * @method static self postDelete()
 * @method static self postRestore()
 * @method static self postForceDelete()
 * @method static self postCommentRead()
 * @method static self postCommentWrite()
 * @method static self postCommentUpdate()
 * @method static self postCommentApprove()
 * @method static self postCommentDelete()
 * @method static self postCommentRestore()
 * @method static self postCommentForceDelete()
 * @method static self postAttachmentRead()
 * @method static self postAttachmentAdd()
 * @method static self postAttachmentUpdate()
 * @method static self postAttachmentDelete()
 * @method static self postAttachmentRestore()
 * @method static self postAttachmentForceDelete()
 */
class PermissionsEnum extends Enum
{
}
