services:
  database:
    image: mysql:8.0
    container_name: database
    tty: true
    ports:
      - "127.0.0.1:3306:3306"
      - "3307:3306"
    volumes:
      - db-storage:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/my.cnf
      - ./docker/mysql/logs:/var/log
      - ./docker/mysql/keys:/usr/local/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    restart: unless-stopped
    networks:
      - blog-net
  db-panel:
    image: phpmyadmin/phpmyadmin:latest
    container_name: db-panel
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_ARBITRARY: 1
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - blog-net
  cache-driver:
    image: redis:latest
    container_name: cache-driver
    ports:
      - "127.0.0.1:6379:6379"
      - "6380:6379"
    restart: unless-stopped
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/logs:/var/opt/redislabs/log/
    networks:
      - blog-net
  # webserver: TODO: Fix problem with nginx server for searching files in storage
  #   image: nginx:latest
  #   container_name: webserver
  #   tty: true
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./:/var/www
  #     - ./storage:/var/www/storage:ro
  #     - ./public:/var/www/public:ro
  #     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./docker/nginx/conf.d:/etc/nginx/conf.d
  #     - ./docker/nginx/snippets:/etc/nginx/snippets
  #     - ./docker/nginx/logs:/var/log/nginx
  #     - ./docker/ssl/swiat-ov.test.key:/etc/ssl/certs/swiat-ov.test.key
  #     - ./docker/ssl/swiat-ov.test.crt:/etc/ssl/certs/swiat-ov.test.crt
  #   restart: unless-stopped
  #   networks:
  #     - blog-net
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    ports:
      - "2222:2222"
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/ini/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/ini/opcache:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/ssl/swiat-ov.test.key:/etc/ssl/certs/swiat-ov.test.key
      - ./docker/ssl/swiat-ov.test.crt:/etc/ssl/certs/swiat-ov.test.crt
    tty: true
    restart: unless-stopped
    depends_on:
      - database
      # - webserver
      - cache-driver
      - mailpit
    networks:
      - blog-net
  mailpit:
    image: axllent/mailpit
    tty: true
    container_name: mailpit
    ports:
      - "8025:8025"
      - "127.0.0.1:1025:1025"
    volumes:
      - ./docker/mailpit/data:/maildir
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailpit
    networks:
      - blog-net
  meilisearch:
    image: getmeili/meilisearch:v1.6.2
    tty: false
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./docker/meilisearch/meili_data:/meili_data:rw
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
    networks:
      - blog-net
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - blog-net
    restart: unless-stopped

networks:
  blog-net:

volumes:
  db-storage:
  grafana-storage:
